
version: 2

models:
    - name: customers_sales
      description: "pruebas" 
      columns:
          - name: CUSTOMER_SK
            description: "Llave del ususario"
            tests:
                - unique
                - not_null